base: "DARK"
colors:
  accent: "#ffca9ee6"
  accentVariant: "#ffca9ee6"
  secondary: "#ffca9ee6"
  secondaryVariant: "#fff4b8e4"
  background: "#ff303446"
  menus: "#ff414559"
  title: "#ffbabbf1"
  accentVariant2: "#ffbabbf1"
  sentMessage: "#ff414559"
  sentReply: "#ff51576d"
  receivedMessage: "#ff414559"
  receivedReply: "#ff51576d"
wallpaper:
  preset: "cats"
  scale: 1.5
  background: "#ff303446"
  tint: "#ff232634"
