base: "DARK"
colors:
  accent: "#ffcba6f7"
  accentVariant: "#ffcba6f7"
  secondary: "#ffcba6f7"
  secondaryVariant: "#fff5c2e7"
  background: "#ff1e1e2e"
  menus: "#ff313244"
  title: "#ffb4befe"
  accentVariant2: "#ffb4befe"
  sentMessage: "#ff313244"
  sentReply: "#ff45475a"
  receivedMessage: "#ff313244"
  receivedReply: "#ff45475a"
wallpaper:
  preset: "cats"
  scale: 1.5
  background: "#ff1e1e2e"
  tint: "#ff11111b"
