base: "LIGHT"
colors:
  accent: "#ff8839ef"
  accentVariant: "#ff8839ef"
  secondary: "#ff8839ef"
  secondaryVariant: "#ffea76cb"
  background: "#ffeff1f5"
  menus: "#ffccd0da"
  title: "#ff7287fd"
  accentVariant2: "#ff7287fd"
  sentMessage: "#ffccd0da"
  sentReply: "#ffbcc0cc"
  receivedMessage: "#ffccd0da"
  receivedReply: "#ffbcc0cc"
wallpaper:
  preset: "cats"
  scale: 1.5
  background: "#ffeff1f5"
  tint: "#ffdce0e8"
